//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEQCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestEQCreator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;uuid&quot;:&quot;096fb714-d536-4f09-849b-a78e1d1a59c8&quot;,&quot;DisplayName&quot;:&quot;默认配置&quot;,&quot;TargetDevice&quot;:&quot;Edifier W820NB&quot;,&quot;RecordingDevice&quot;:&quot;人耳（成年男性，21岁，听力良好）&quot;,&quot;Params&quot;:[{&quot;freq&quot;:135,&quot;dbGain&quot;:-16.5},{&quot;freq&quot;:150,&quot;dbGain&quot;:-21.4000015},{&quot;freq&quot;:176,&quot;dbGain&quot;:-22.9000015},{&quot;freq&quot;:200,&quot;dbGain&quot;:-22.5},{&quot;freq&quot;:225,&quot;dbGain&quot;:-23.5},{&quot;freq&quot;:256,&quot;dbGain&quot;:-26.4000015},{&quot;freq&quot;:288,&quot;dbGain&quot;:-27.7},{&quot;freq&quot;:340,&quot;dbGain&quot;:-27.5},{&quot;freq&quot;:408,&quot;dbGain&quot;:-27.9000015},{&quot;freq&quot;:468,&quot;dbGain&quot;:-27.7},{&quot;freq&quot;:536,&quot;dbGain&quot;:-28.8},{&quot;freq&quot;:618,&quot;dbGain&quot;:-30.3},{&quot;fr [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string buildinHsvt {
            get {
                return ResourceManager.GetString("buildinHsvt", resourceCulture);
            }
        }
    }
}
